### ISSUE TITLE
scikit-learn tip #37: issue with set_config() function

### ISSUE THREAD

**Issue by Xavier-F** [justmarkham/scikit-learn-tips#5]
Dear all,

Thanks to the fantastic work from Kevin to spread his data science knowledges accross the web, I discovered this new pipeline interactive diagramm in sklearn v0.23. I tried to use it on one of my jupyter notebook after ruing a conda update --all, to ensure no compatibility issues, and I am really struggeling with it. 
I can import the package. But when I just try to set display parameter to 'diagram', it is just telling me "set_config() got an unexpected keyword argument 'display'"

![Screenshot_1](https://user-images.githubusercontent.com/66141230/83301487-0bcb7300-a1fa-11ea-91ab-7518bef24dd4.png)

I am searching to fix this issue on my notebook since nearly 1 h, but impossible to find what went wrong. Does anyone have an idea on how to run this new function?

Thanks a lot for your support, and take good care!

**Comment by ericabrauer** [comment]
The first thing I would do is to run help(set_config). It may be that the function only accepts positional arguments. Hope this helps!

**Comment by akanz1** [comment]
Can you check the scikit-learn version being used by the currently active ipython kernel? 

`sklearn.__version__`

Also make sure the package is up to date in your currently active virtual environment or switch to base if that's where you updated to 0.0.23.

**Comment by justmarkham** [comment]
@Xavier-F Thanks for your kind words!

I agree with @akanz1, definitely check your sklearn version, since you will need 0.23:

```
import sklearn
sklearn.__version__
```

And with conda, you can check your versions with `conda list`

Hope that helps!

**Comment by Xavier-F** [comment]
Dear Erica, Andreas and Kevin

Thanks a lot for your super prompt support. Indeed, seems that the conda update --all only update scikit learn package toward 0.22 version. 
I just tried again with pip install --upgrade scikit-learn, and looks like all is runing smoothly now on my notebook.

Once again thanks a lot, and take good care

**Comment by cpumarfrohberg** [comment]
Dear scikit-learn devs,
I also want to thank you for the awesome features of vs. 1.2.0!
When calling `fit_transform()` on my DataFrame like so:

`from sklearn.preprocessing import MinMaxScaler, StandardScaler, KBinsDiscretizer
from sklearn.compose import make_column_transformer
from sklearn import set_config
set_config(transform_output = 'pandas')

discretizable = [<col_one>, <col_two>, ..., <col_n>]
scalable = [<other_col_one>, <other_col_two>, ..., <other_col_n>]

discretizer = KBinsDiscretizer()
scaler = MinMaxScaler()

preprocessor = make_column_transformer( 
        (scaler, scalable),
        (discretizer, discretizable),
        remainder='passthrough'
        )
X_feature_engineered = preprocessor.fit_transform(df)`

A type error is raised:
`ValueError: Pandas output does not support sparse data.`

I notice that the percent of '0' in my data ~45%.

Why does this matter when calling `set_config()`? What can I do in order to keep column names after transformation?

Thanks in advance!
